"""Shared logic for Window Sizer.

Owns the presets file, generates the KWin script from those presets, loads the
script into KWin, and triggers a preset's resize action over DBus. Both the tray
app and the presets editor import from here so there is a single source of truth.
"""

import json
import subprocess
import uuid
from pathlib import Path

CONFIG_DIRECTORY = Path.home() / ".config" / "window-sizer"
PRESETS_PATH = CONFIG_DIRECTORY / "presets.json"
GENERATED_SCRIPT_PATH = CONFIG_DIRECTORY / "window-sizer.js"

# Name KWin/kglobalaccel uses to identify this loaded script.
KWIN_PLUGIN_NAME = "window_sizer"
# kglobalaccel groups every KWin-script shortcut under this component.
KGLOBALACCEL_COMPONENT = "kwin"

VALID_POSITIONS = ("keep", "center")

DEFAULT_PRESETS = [
    {"name": "720p", "width": 1280, "height": 720, "position": "keep"},
    {"name": "720p centered", "width": 1280, "height": 720, "position": "center"},
    {"name": "1080p", "width": 1920, "height": 1080, "position": "keep"},
    {"name": "Half HD", "width": 960, "height": 1080, "position": "keep"},
    {"name": "Compact", "width": 800, "height": 600, "position": "center"},
]


def run_qdbus(object_path, method, *arguments):
    """Call a method on the org.kde.KWin / kglobalaccel DBus service.

    Returns the trimmed stdout string, or None if qdbus reported an error.
    """
    command = ["qdbus", _service_for(object_path), object_path, method, *map(str, arguments)]
    completed = subprocess.run(command, capture_output=True, text=True)
    if completed.returncode != 0:
        return None
    return completed.stdout.strip()


def _service_for(object_path):
    if object_path.startswith("/component") or "kglobalaccel" in object_path:
        return "org.kde.kglobalaccel"
    return "org.kde.KWin"


def action_name_for(preset):
    """Stable kglobalaccel action id for a preset. Survives renames so any
    keyboard shortcut the user assigns in System Settings stays bound."""
    return "WindowSizer_" + preset["identifier"]


def preset_label(preset):
    suffix = " · centered" if preset.get("position") == "center" else ""
    return f"{preset['name']} ({preset['width']}×{preset['height']}){suffix}"


def ensure_config_exists():
    CONFIG_DIRECTORY.mkdir(parents=True, exist_ok=True)
    if not PRESETS_PATH.exists():
        save_presets([_with_identifier(preset) for preset in DEFAULT_PRESETS])


def _with_identifier(preset):
    copied = dict(preset)
    copied.setdefault("identifier", uuid.uuid4().hex[:8])
    copied.setdefault("position", "keep")
    return copied


def load_presets():
    ensure_config_exists()
    with open(PRESETS_PATH, "r", encoding="utf-8") as presets_file:
        raw_presets = json.load(presets_file)
    return [_with_identifier(preset) for preset in raw_presets]


def save_presets(presets):
    CONFIG_DIRECTORY.mkdir(parents=True, exist_ok=True)
    normalized = [_with_identifier(preset) for preset in presets]
    with open(PRESETS_PATH, "w", encoding="utf-8") as presets_file:
        json.dump(normalized, presets_file, indent=2)
    return normalized


def generate_script(presets):
    """Bake the preset list into a KWin JavaScript file. Each preset becomes a
    named shortcut that resizes (and optionally re-centers) the active window."""
    script_presets = [
        {
            "actionName": action_name_for(preset),
            "label": "Just Right: " + preset_label(preset),
            "width": int(preset["width"]),
            "height": int(preset["height"]),
            "position": preset.get("position", "keep"),
        }
        for preset in presets
    ]
    presets_literal = json.dumps(script_presets)

    script_source = f"""// Generated by Window Sizer. Do not edit by hand.
var windowSizerPresets = {presets_literal};

function applyToActiveWindow(targetWidth, targetHeight, position) {{
    var activeWindow = workspace.activeWindow;
    if (activeWindow === null) {{
        return;
    }}

    var win = activeWindow;

    function doResize() {{
        var currentGeometry = win.frameGeometry;
        var newX = currentGeometry.x;
        var newY = currentGeometry.y;
        if (position === "center") {{
            var area = workspace.clientArea(KWin.MaximizeArea, win);
            newX = area.x + Math.round((area.width - targetWidth) / 2);
            newY = area.y + Math.round((area.height - targetHeight) / 2);
        }}
        // Qt.rect() is QML-only; plain JS objects are converted to QRectF
        // via KWin's registered QJSValue→QRectF meta-type converter.
        win.frameGeometry = {{ x: newX, y: newY, width: targetWidth, height: targetHeight }};
    }}

    // Detect maximized state by geometry rather than maximizeMode, which
    // returns a Qt flags object in KWin 6 scripting — truthy for all windows.
    var screenArea = workspace.clientArea(KWin.MaximizeArea, win);
    var geo = win.frameGeometry;
    var needsUnmaximize = win.fullScreen ||
        (geo.x <= screenArea.x + 4 && geo.y <= screenArea.y + 4 &&
         geo.width >= screenArea.width - 4 && geo.height >= screenArea.height - 4);

    if (win.fullScreen) {{
        win.fullScreen = false;
    }}
    win.setMaximize(false, false);

    if (needsUnmaximize) {{
        // setMaximize is async on Wayland: KWin restores the pre-maximize
        // geometry after our JS returns, overwriting a same-tick frameGeometry.
        // Wait for frameGeometryChanged (fires once KWin has settled the
        // restored geometry), then stamp our target size on top.
        var handler = function () {{
            win.frameGeometryChanged.disconnect(handler);
            doResize();
        }};
        win.frameGeometryChanged.connect(handler);
    }} else {{
        doResize();
    }}
}}

for (var presetIndex = 0; presetIndex < windowSizerPresets.length; presetIndex++) {{
    (function (preset) {{
        registerShortcut(preset.actionName, preset.label, "", function () {{
            applyToActiveWindow(preset.width, preset.height, preset.position);
        }});
    }})(windowSizerPresets[presetIndex]);
}}
"""
    CONFIG_DIRECTORY.mkdir(parents=True, exist_ok=True)
    with open(GENERATED_SCRIPT_PATH, "w", encoding="utf-8") as script_file:
        script_file.write(script_source)
    return GENERATED_SCRIPT_PATH


def reload_kwin_script():
    """Regenerate the script from the saved presets and (re)load it into KWin."""
    presets = load_presets()
    generate_script(presets)
    run_qdbus("/Scripting", "org.kde.kwin.Scripting.unloadScript", KWIN_PLUGIN_NAME)
    run_qdbus("/Scripting", "org.kde.kwin.Scripting.loadScript",
              str(GENERATED_SCRIPT_PATH), KWIN_PLUGIN_NAME)
    run_qdbus("/Scripting", "org.kde.kwin.Scripting.start")
    return presets


def trigger_preset(preset):
    """Fire a preset's action, resizing whatever window is currently active."""
    return run_qdbus("/component/" + KGLOBALACCEL_COMPONENT,
                     "org.kde.kglobalaccel.Component.invokeShortcut",
                     action_name_for(preset))
