"""Shared logic for Window Sizer.

Owns the presets file, generates the KWin script from those presets, loads the
script into KWin, and triggers a preset's resize action over DBus. Both the tray
app and the presets editor import from here so there is a single source of truth.
"""

import json
import shutil
import subprocess
import sys
import uuid
from pathlib import Path

CONFIG_DIRECTORY = Path.home() / ".config" / "window-sizer"
PRESETS_PATH = CONFIG_DIRECTORY / "presets.json"
GENERATED_SCRIPT_PATH = CONFIG_DIRECTORY / "window-sizer.js"

# Name KWin/kglobalaccel uses to identify this loaded script.
KWIN_PLUGIN_NAME = "window_sizer"
# kglobalaccel groups every KWin-script shortcut under this component.
KGLOBALACCEL_COMPONENT = "kwin"

VALID_POSITIONS = ("keep", "center")

DEFAULT_PRESETS = [
    {"name": "720p", "width": 1280, "height": 720, "position": "keep"},
    {"name": "720p centered", "width": 1280, "height": 720, "position": "center"},
    {"name": "1080p", "width": 1920, "height": 1080, "position": "keep"},
    {"name": "Half HD", "width": 960, "height": 1080, "position": "keep"},
    {"name": "Compact", "width": 800, "height": 600, "position": "center"},
]

# Prefer the Qt6 qdbus binary; fall back to the Qt5 one if needed.
_QDBUS = next(
    (cmd for cmd in ("qdbus6", "qdbus-qt6", "qdbus") if shutil.which(cmd)),
    "qdbus",
)


def run_qdbus(object_path, method, *arguments):
    """Call a method on the org.kde.KWin / kglobalaccel DBus service.

    Returns the trimmed stdout string, or None if the call failed.
    """
    command = [_QDBUS, _service_for(object_path), object_path, method, *map(str, arguments)]
    try:
        completed = subprocess.run(command, capture_output=True, text=True, timeout=5)
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return None
    if completed.returncode != 0:
        return None
    return completed.stdout.strip()


def _service_for(object_path):
    if object_path.startswith("/component") or "kglobalaccel" in object_path:
        return "org.kde.kglobalaccel"
    return "org.kde.KWin"


def action_name_for(preset):
    """Stable kglobalaccel action id for a preset. Survives renames so any
    keyboard shortcut the user assigns in System Settings stays bound."""
    return "WindowSizer_" + preset["identifier"]


def preset_label(preset):
    suffix = " · centered" if preset.get("position") == "center" else ""
    return f"{preset['name']} ({preset['width']}×{preset['height']}){suffix}"


def ensure_config_exists():
    CONFIG_DIRECTORY.mkdir(parents=True, exist_ok=True)
    if not PRESETS_PATH.exists():
        save_presets([_with_identifier(preset) for preset in DEFAULT_PRESETS])


def _with_identifier(preset):
    copied = dict(preset)
    copied.setdefault("identifier", uuid.uuid4().hex[:8])
    copied.setdefault("position", "keep")
    return copied


def load_presets():
    ensure_config_exists()
    try:
        with open(PRESETS_PATH, "r", encoding="utf-8") as presets_file:
            raw_presets = json.load(presets_file)
    except (json.JSONDecodeError, ValueError):
        print(
            f"Warning: {PRESETS_PATH} is corrupted — falling back to defaults.",
            file=sys.stderr,
        )
        raw_presets = list(DEFAULT_PRESETS)
    return [_with_identifier(preset) for preset in raw_presets]


def save_presets(presets):
    CONFIG_DIRECTORY.mkdir(parents=True, exist_ok=True)
    normalized = [_with_identifier(preset) for preset in presets]
    # Write atomically: write to a temp file then rename (POSIX rename is atomic,
    # so a crash mid-write never leaves presets.json truncated or partial).
    tmp_path = PRESETS_PATH.with_suffix(".tmp")
    with open(tmp_path, "w", encoding="utf-8") as presets_file:
        json.dump(normalized, presets_file, indent=2)
    tmp_path.replace(PRESETS_PATH)
    return normalized


def generate_script(presets):
    """Bake the preset list into a KWin JavaScript file. Each preset becomes a
    named shortcut that resizes (and optionally re-centers) the active window."""
    script_presets = [
        {
            "actionName": action_name_for(preset),
            "label": "Just Right: " + preset_label(preset),
            "menuLabel": preset_label(preset),
            "width": int(preset["width"]),
            "height": int(preset["height"]),
            "position": preset.get("position", "keep"),
        }
        for preset in presets
    ]
    presets_literal = json.dumps(script_presets)

    script_source = f"""// Generated by Window Sizer. Do not edit by hand.
var windowSizerPresets = {presets_literal};

function applyToActiveWindow(targetWidth, targetHeight, position, windowOverride) {{
    var win = windowOverride || workspace.activeWindow;
    if (!win) {{
        return;
    }}

    // Cancel any in-flight resize on this window (rapid double-trigger safety).
    if (win._sizerHandler) {{
        try {{ win.frameGeometryChanged.disconnect(win._sizerHandler); }} catch (e) {{}}
        win._sizerHandler = null;
    }}

    function doResize() {{
        win._sizerHandler = null;
        var currentGeometry = win.frameGeometry;
        var newX = currentGeometry.x;
        var newY = currentGeometry.y;
        if (position === "center") {{
            var area = workspace.clientArea(KWin.MaximizeArea, win);
            newX = area.x + Math.round((area.width - targetWidth) / 2);
            newY = area.y + Math.round((area.height - targetHeight) / 2);
        }}
        // Qt.rect() is QML-only; plain JS objects are converted to QRectF
        // via KWin's registered QJSValue→QRectF meta-type converter.
        win.frameGeometry = {{ x: newX, y: newY, width: targetWidth, height: targetHeight }};
        // KWin clamps to the app's declared minSize before applying; if the
        // resulting size differs from what we asked, surface that to the user.
        var actual = win.frameGeometry;
        if (actual.width !== targetWidth || actual.height !== targetHeight) {{
            callDBus("org.justright.tray", "/SizeOverlay",
                     "", "showClamped",
                     targetWidth, targetHeight,
                     Math.round(actual.width), Math.round(actual.height));
        }}
    }}

    function deferResize() {{
        var handler = function () {{
            win.frameGeometryChanged.disconnect(handler);
            win._sizerHandler = null;
            doResize();
        }};
        win._sizerHandler = handler;
        win.frameGeometryChanged.connect(handler);
    }}

    // Fullscreen: attach the handler BEFORE changing state so we never miss the
    // signal if KWin fires it synchronously during the property assignment.
    if (win.fullScreen) {{
        deferResize();
        win.fullScreen = false;
        return;
    }}

    // maximizeMode returns a Qt flags object in KWin 6 scripting — plain == comparisons
    // are useless (always truthy), but bitwise & coerces it to a number correctly.
    // Bit 1 = vertically maximized, bit 2 = horizontally maximized.
    // Skip tiled windows: they are not maximized and setMaximize would break tiling.
    var isTiled = win.tile !== null && win.tile !== undefined;
    var isMaximized = !isTiled && (win.maximizeMode & 3) === 3;

    win.setMaximize(false, false);

    if (isMaximized) {{
        // setMaximize is async on Wayland: KWin restores the pre-maximize geometry
        // after our JS returns, overwriting a same-tick frameGeometry assignment.
        // Wait for frameGeometryChanged (fires once KWin has settled the restored
        // geometry), then stamp our target size on top.
        deferResize();
    }} else {{
        doResize();
    }}
}}

for (var presetIndex = 0; presetIndex < windowSizerPresets.length; presetIndex++) {{
    (function (preset) {{
        registerShortcut(preset.actionName, preset.label, "", function () {{
            applyToActiveWindow(preset.width, preset.height, preset.position);
        }});
    }})(windowSizerPresets[presetIndex]);
}}

// Add a "Just Right" submenu to the window title-bar right-click context menu.
registerUserActionsMenu(function (win) {{
    return {{
        text: "Just Right",
        items: windowSizerPresets.map(function (preset) {{
            return {{
                text: preset.menuLabel,
                triggered: function () {{
                    applyToActiveWindow(preset.width, preset.height, preset.position, win);
                }}
            }};
        }})
    }};
}});

// ---------------------------------------------------------------------------
// Geometry tooltip: show a size overlay whenever any window is resized.
// Calls back to the tray app over DBus; the tray renders the overlay widget.
// ---------------------------------------------------------------------------
var _wsTooltipLastT = 0;

function wsNotifySize(win) {{
    var geo = win.frameGeometry;
    // Only fire when *this window's* size changes, not on plain moves.
    if (geo.width === win._wsLastW && geo.height === win._wsLastH) return;
    // Throttle to ~15 fps so we don't hammer DBus on every pixel.
    var now = Date.now();
    if (now - _wsTooltipLastT < 66) return;
    win._wsLastW = geo.width;
    win._wsLastH = geo.height;
    _wsTooltipLastT = now;
    callDBus("org.justright.tray", "/SizeOverlay",
             "", "showSize",
             Math.round(geo.x), Math.round(geo.y),
             Math.round(geo.width), Math.round(geo.height));
}}

function wsConnectWindow(win) {{
    // Seed the per-window size so the first frameGeometryChanged only fires
    // if the size actually changes (not on the first plain move).
    var geo = win.frameGeometry;
    win._wsLastW = geo.width;
    win._wsLastH = geo.height;
    win.frameGeometryChanged.connect(function() {{ wsNotifySize(win); }});
}}

// Connect to all windows already open, then to any that open later.
var _wsAllWindows = (typeof workspace.windowList === "function")
    ? workspace.windowList()
    : (workspace.windows || []);
for (var _wsIdx = 0; _wsIdx < _wsAllWindows.length; _wsIdx++) {{
    wsConnectWindow(_wsAllWindows[_wsIdx]);
}}
workspace.windowAdded.connect(wsConnectWindow);

// ---------------------------------------------------------------------------
// "Add current window size" shortcut — reads the active window's geometry
// and sends it to the tray so the user can save it as a new preset.
// ---------------------------------------------------------------------------
registerShortcut("WindowSizer_AddCurrentSize", "Just Right: Add current window size", "", function() {{
    var win = workspace.activeWindow;
    if (!win) return;
    var geo = win.frameGeometry;
    callDBus("org.justright.tray", "/SizeOverlay",
             "", "addCurrentSize",
             Math.round(geo.width), Math.round(geo.height));
}});
"""
    CONFIG_DIRECTORY.mkdir(parents=True, exist_ok=True)
    with open(GENERATED_SCRIPT_PATH, "w", encoding="utf-8") as script_file:
        script_file.write(script_source)
    return GENERATED_SCRIPT_PATH


def reload_kwin_script():
    """Regenerate the script from the saved presets and (re)load it into KWin."""
    presets = load_presets()
    generate_script(presets)
    run_qdbus("/Scripting", "org.kde.kwin.Scripting.unloadScript", KWIN_PLUGIN_NAME)
    run_qdbus("/Scripting", "org.kde.kwin.Scripting.loadScript",
              str(GENERATED_SCRIPT_PATH), KWIN_PLUGIN_NAME)
    run_qdbus("/Scripting", "org.kde.kwin.Scripting.start")
    return presets


def trigger_preset(preset):
    """Fire a preset's action, resizing whatever window is currently active."""
    return run_qdbus("/component/" + KGLOBALACCEL_COMPONENT,
                     "org.kde.kglobalaccel.Component.invokeShortcut",
                     action_name_for(preset))
